### ISSUE TITLE
worm on a string

### ISSUE THREAD

**Issue by worm-on-a-string** [kassindornelles/BXVK.NET#4]
the orange one will eat you

dont believe the fake news media

dont believe th

the fbi are trying to keep him under the cia wraps and stop him as he is evrioenmtn bad for us!! please help fix the issue in your progfram

SAVE US.

![worm-on-a-string-4456541](https://user-images.githubusercontent.com/47217123/52061184-ae6fd500-2565-11e9-85ed-b169984749d6.png)

**Comment by kassindornelles** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by worm-on-a-string** [comment]
t̴̛͙̘̮̤̞̘͙̫̺̞̩̳̀̒͗͋̃̐̽́̒͋̊͗͋͜h̷̡͈̯̞̹̤͈̟̗̝̊͒̇̐͂͋̅̀͒̏̀̿̚̕͝ͅe̵̡̞̔ ̴̢̨̝͇̩͍͎̬͕̯̟̮͔̎̇̽̒̅͠͝ͅw̶̛̬̝͈̩͕̰̫̩̮͍̞̍͑̏͋̀̈́̏̄̆̓͋̄͝ó̶̢̪͙̮͓̫̩̮̈̄̆͛̇ͅr̸̩̓̂̓͗̌̀͐̕͘͠m̴̫̳̟̣̋̅͛͜͝ ̴͖̫̼̩͙̖͓̾͒͒͋͝͝͠w̶̙̮̱̝̘͎̗̖̦̏͜i̸̫̬̳̗̠̻̝̰̰̩̭͓̱̖͑̎̇́̀̈̾̀l̷̛͍̰͖͚̤͒͆͒̈́̒̐̍̍̈̈́̄̀ḷ̸̘̭̐͒̾̓͋́͝ ̷̨̡̢̛̛̗͚͓̗̖̝̩̫̖͖͇̈́̐̔̔̋̽̆́͑̕͜͝é̸̡̤̲͈̫̠̗̟̝̙̉̊̒͛̓̎͐̓̓͋a̵̢̛̘̫͖̖͕͓̤͇̞͖͕͉̍̔̀͐̍͑͑̌̿͘͝ť̷̡̥̻̲̖͇̟̳̄͋͛͋͛̕̕͠ ̸̡͔̘̭̺̬̼̳̮̀̿ͅͅy̷̢̡̨͓̥̫̥͎̺͕̔̌̆̔̽̑͋͐͠ơ̴̬̹̻̘̇̃́͌͋̈́̆͊̎̐̈̓̚͝u̵̧̧̨̳͔̳̭̜̠͎͈̜͋̄͂̅̊̅̀̈́̅͌̐͂͝͠ ̷̛̦̳̖̟̞̉ͅi̷̤̭̞̜̰͉͔̳̥̻͗͜͝n̴̫͙̞̦͈̟̳̻͈̪̮͆̔̔ ̸̡̛̳̪̼̝̞̤̦͎̫͛̓̆y̴̢̯̯͓͎͎̯̭̑͌̌̌̈͑́̿͝o̵̢̡̤̺̭̪̟̥͙̞͂̄̽̇͂̐̌̚͘͜ù̸̙̯͚̝̳̪̼͕̺̬͉̥͙͗͌̅͐͊́͂̀͐̏́̍̕͝ͅr̶͙̹̻̺̿͌͗͗͘͘͝ ̷̨̥̟̱̞̭̲͔̱͈̠̆̃̿͝s̷̨͕̼̻̘̙̣͈̹̥̜͓̺̩̓̾͌̓̓͋̽̍̅̀͗͌̇͋̓͜l̶̨̟̫̼̰̻̱̳̙̩̩̋̄̚ē̶̡̨̤͍̻͖̱͓̞̣̞͗̂̓͗̈́̃̕͜͠͝͝e̸̛̠̪̤̼͚͆̀̇͋̑̂̒̊̈́̽̒̄͘̕p̵̮̣̀ ̵̛̝͍̮̣̳͔̤̣̲̬̟̇͒̂̄͝a̸̺̞̽̀̅̌̂̓̈̀́͛̇͠͝ņ̴̖̪͎̣͖̤͓͒̓͛̾̽͌̉͠d̶̲͖̠̣̙̹̘̘̝̙͍̎̽̑̈́͋̓̕͝ͅ ̵̧̨̨͈̞͇̣̟̞̲̟͕̖̳͆͒̉̔́̈́̐͋̒́̐͝d̸͍̦̪̹͇̼̜͑̃͌̓͆̂̊̄̇̒̀͂͘͝ͅê̵̲̆̃v̷͖̭̩̯̦̮̣̗̐̏̋̒͌͂͝͠õ̴̱̱͍̠͕̺̪̟̋̂̀̑̚͜͜͠ǔ̸͔̞̯̉͗́̆̒̓͗r̷̨̧̬͎͉̮̪̬̮̹̹̺̖̓̄ͅ ̷̨̧̫̦̮̲̱͉̳̭̳̲̘͋̉̇̽̓̋̽̎̈́̔̉͘͝y̸͎͖̺̾͑́́͌͋̈́͑̈́͝͝ơ̶̙̜̝̜̪͔̮͕͓͎͓͆̿̋̇̇̃ū̶̥͕͓͚̟͇̪̪̝̟̜̌̈̾̈́͊̌̉̾͊̕̚͝͝ͅŗ̴̛͎̼̬̝̰͙̹̹̩̱̙̮̈̈̊̀̔̄̿́̅͘ ̷͔̗̫̳̼̂̈͆̈́̈́̚͝͝ȍ̵̟̐͊̿̔͒͆̎͠r̸̗͚͖̔̋̆̅̃̊͋̒͐́̈́́̚͠͠g̸̢̧̛̤̙̝̼̺̲̼̭̺͑̓ą̶̻͓̻̱̪͍̞͍̦̏̄͒͜͜͝n̵͎̜̅̈̓̈́͂̋̀̒̀̓̽̀̌̎s̸̢̨̖̖̘̬̼̞͍͎̻̈́̇ ̵̨̧̡̦̰͉̤̮̭̯͓̟̫̉̌̑̆̎́̄͒̄͒̔̽͂̀w̷̡͈̪͍͖̗̯͂̌̊̆́̆̕̕͜h̴̨̧̯͔͙͓̲͕̮̔̈́́̾͆̂̕̕ͅȍ̴̡͚̜̦͜ļ̴͕̪̱̩̟͖̜̫̺̼̯̬̌̉̔́͒̈̎̏̑̓̚̚ͅé̸̞ ̷̦̝̠̰͉̭̠̗̙̗͍͌̆̐͌̏̓͛̄́͂͂͆͘̚̚
